### ISSUE TITLE
ipv6 disable issues

### ISSUE THREAD

**Issue by jgrill** [chef-cookbooks/firewall#91]
I'm working on CentOS 6.6 with iptables and ipv6 disabled (kernel module not loaded) and have encountered two issues.

First, the new "ipv6_enabled" parameter to the firewall resource precludes including the default recipe, if you need to set it to false. This is due to the firewall resource being called with the install action in default.rb. Maybe this could be a feature request to have an attribute to turn on/off ipv6 support rather then having to include it as a parameter to the firewall resource.

Second, I'm getting undefined method `key?' for nil:NilClass with the example below. This only occurs when disabling ipv6 via the firewall resource.

My wrapper...

```ruby
firewall 'default' do
  action :install
  ipv6_enabled false
end

firewall_rule 'allow world to ssh' do
  port 22
  source '0.0.0.0/0'
end

# allow established connections
firewall_rule 'established' do
  stateful [:related, :established]
  protocol :none # explicitly don't specify protocol
  command :allow
end
[snip]
```

Log output...
```
[snip]
Compiling Cookbooks...
       Converging 8 resources
       Recipe: efx_firewall::default

           - install iptables and enable/start services
        (up to date)
         * file[create empty /etc/sysconfig/iptables] action create (skipped due to not_if)
        (up to date)
        (up to date)
         * firewall_rule[allow world to ssh] action create

         * firewall_rule[established] action create

           ================================================================================
           Error executing action `create` on resource 'firewall_rule[established]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `key?' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_rule_iptables.rb:51:in `block (2 levels) in <class:FirewallRuleIptables>'
           /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_rule_iptables.rb:45:in `each'
           /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_rule_iptables.rb:45:in `block in <class:FirewallRuleIptables>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/efx_firewall/recipes/default.rb

            22: firewall_rule 'established' do
            23:   stateful [:related, :established]
            24:   protocol :none # explicitly don't specify protocol
            25:   command :allow
            26: end
            27:
            28: # Allow all loopback traffic
            29: firewall_rule 'loopback' do
            30: 	interface 'lo'
            31: 	command :allow
            32: end
            33:
            34: execute 'dummy-delay-iptables-save' do
            35: 	command '/bin/true'
            36: 	notifies :run, 'execute[iptables-save]', :delayed
            37: end
            38:
            39: execute 'iptables-save' do
            40:   command 'service iptables save'
            41:   action :nothing
            42: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/efx_firewall/recipes/default.rb:22:in `from_file'

           firewall_rule("established") do
             action [:create]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :firewall_rule
             cookbook_name "efx_firewall"
             recipe_name "default"
             stateful [:related, :established]
             protocol :none
             command :allow
             firewall_name "default"
             direction :in
             description "established"
             position 50
           end


           * file[/etc/sysconfig/iptables] action create (up to date)
            (up to date)

       Running handlers:
       [2015-09-11T14:54:40+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-09-11T14:54:40+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 4.527059018 seconds
       [2015-09-11T14:54:40+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-09-11T14:54:40+00:00] ERROR: firewall_rule[established] (efx_firewall::default line 22) had an error: NoMethodError: undefined method `key?' for nil:NilClass
       [2015-09-11T14:54:40+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by martinb3** [comment]
Hi @jgrill -- thanks for reporting this. This has been a tricky feature to test without having good ipv6-disabled images under kitchen-rackspace and kitchen-vagrant. 

I've applied a small fix, and tested it as much as possible easily. I've pushed it as branch 'ipv6_disable_fixes'. Can you give that a try and let me know if that resolves your issue? It provides an attribute for ipv6_enabled as well as a logic fix for that `nil.key?` error.

If it works for you, I'll go ahead and release it. Thank you!!!

**Comment by jgrill** [comment]
I'm on it! :)

**Comment by jgrill** [comment]
That worked!

**Comment by martinb3** [comment]
Thank you for testing that! I'm merging in one more thing and then I'll release a 2.0.3 version.

**Comment by jgrill** [comment]
Thank you!
